#!/usr/bin/env Rscript
args<-commandArgs(TRUE);if(length(args)!=3L)stop("Usage: first_effects second_effects outdir")
f1<-args[1];f2<-args[2];out<-args[3];if(dir.exists(out))stop("Refusing to overwrite: ",out);dir.create(out,recursive=TRUE)
a<-read.delim(f1,check.names=FALSE,stringsAsFactors=FALSE,quote="");b<-read.delim(f2,check.names=FALSE,stringsAsFactors=FALSE,quote="")
a<-a[a$is_primary_contrast%in%c(TRUE,"TRUE"),]; stopifnot(nrow(a)==24L,nrow(b)==16L)
genera<-c("Morchella","Mortierella","Alternaria","Botryotrichum","Terrimonas","Gemmata","Chitinophaga","Pseudarthrobacter")
marker<-c("ITS","ITS","ITS","ITS","16S","16S","16S","16S");tier<-c(rep("PRIMARY_CORE",3),"SUPPORTING_CORE",rep("PRIMARY_CORE",4));expected<-c("down","up","down","context_dependent","up","down","up","down")
grades<-c("partially_supported","context_dependent","insufficient_external_evidence","context_dependent","context_dependent","externally_opposed","context_dependent","partially_supported")
rationale<-c("first external system supports decrease; second system trends down but is weak or split-driven","first system supports increase; second independent system shows robust decreases in both contrasts","mostly sparse detection; downward signs are not robust enough for replication","first system consistently increases; second system is rare/decreasing or absent","first system supports increase; second system is near-zero or decreases","first system opposes frozen decrease and second system also trends upward, though sparse","support varies by stage/year and includes opposite or unstable contrasts","first system supports decrease; second system does not detect the genus")
class_system<-function(z){c(supported=sum(z$direction_class=="direction_supported"),opposed=sum(z$direction_class=="direction_opposed"),no_clear=sum(z$direction_class=="detected_no_clear_effect"),not_detected=sum(z$direction_class=="not_detected"),not_testable=sum(z$direction_class=="not_testable"))}
rows<-lapply(seq_along(genera),function(i){x<-class_system(a[a$genus==genera[i],]);y<-class_system(b[b$genus==genera[i],]);data.frame(marker=marker[i],genus=genera[i],frozen_tier=tier[i],frozen_expected_direction=expected[i],first_system_supported=x[1],first_system_opposed=x[2],first_system_no_clear=x[3],first_system_not_detected=x[4],second_system_supported=y[1],second_system_opposed=y[2],second_system_no_clear=y[3],second_system_not_detected=y[4],testable_external_systems=2,final_evidence_grade=grades[i],grade_rationale=rationale[i])})
matrix<-do.call(rbind,rows)
write.table(matrix,file.path(out,"final_cross_project_evidence_matrix.tsv"),sep="\t",quote=FALSE,row.names=FALSE)
a$external_system<-"PRJNA935967/PRJNA993383_same_experiment";b$external_system<-"PRJNA822526_independent_experiment";common<-intersect(names(a),names(b));effects<-rbind(a[,common],b[,common]);write.table(effects,file.path(out,"final_external_effect_sizes.tsv"),sep="\t",quote=FALSE,row.names=FALSE,na="")
bot<-b[b$genus=="Botryotrichum",];bot$corrected_heterogeneity_class<-"no_clear_effect";bot$correction_reason<-"M1 detected only in one control operational split and M2 not detected; consistent_down would overstate evidence";write.table(bot,file.path(out,"Botryotrichum_heterogeneity_corrected_v2.tsv"),sep="\t",quote=FALSE,row.names=FALSE,na="")
status_level<-c("direction_supported","direction_opposed","detected_no_clear_effect","not_detected","not_testable")
status_col<-c(direction_supported="#2A9D8F",direction_opposed="#D45D4C",detected_no_clear_effect="#B7B7B7",not_detected="#ECECEC",not_testable="#FFFFFF")
grade_col<-c(externally_replicated="#117864",partially_supported="#5AB4AC",context_dependent="#E6A23C",externally_opposed="#C44E52",insufficient_external_evidence="#BDBDBD")
short<-c(Morchella="Morchella",Mortierella="Mortierella",Alternaria="Alternaria",Botryotrichum="Botryotrichum",Terrimonas="Terrimonas",Gemmata="Gemmata",Chitinophaga="Chitinophaga",Pseudarthrobacter="Pseudarthrobacter")
cell_status<-function(g,source,contrast=NULL){z<-if(source=="first")a[a$genus==g,]else b[b$genus==g,];if(!is.null(contrast))z<-z[z$tested_contrast==contrast,];if(!nrow(z))return("not_testable");if(any(z$direction_class=="direction_supported"))return("direction_supported");if(any(z$direction_class=="direction_opposed"))return("direction_opposed");if(any(z$direction_class=="detected_no_clear_effect"))return("detected_no_clear_effect");if(all(z$direction_class=="not_detected"))return("not_detected");"not_testable"}
mat<-sapply(c("First external system","PRJNA822526 M1/CK1","PRJNA822526 M2/CK2"),function(src)sapply(genera,function(g)if(src=="First external system")cell_status(g,"first")else cell_status(g,"second",if(grepl("M1",src))"M1_vs_CK1"else"M2_vs_CK2")))
rownames(mat)<-genera
draw_main<-function(){layout(matrix(c(1,1,2,3),2,2,byrow=TRUE),widths=c(1.65,1),heights=c(1,1));par(family="Arial",cex=0.85)
 par(mar=c(6,9,2,1));plot.new();plot.window(xlim=c(.5,ncol(mat)+1.5),ylim=c(.5,nrow(mat)+.5));for(i in seq_len(nrow(mat)))for(j in seq_len(ncol(mat)))rect(j,nrow(mat)-i+1,j+1,nrow(mat)-i+2,col=status_col[mat[i,j]],border="white");for(i in seq_len(nrow(mat)))rect(ncol(mat)+.15,nrow(mat)-i+1,ncol(mat)+1.15,nrow(mat)-i+2,col=grade_col[matrix$final_evidence_grade[i]],border="white");axis(1,at=c(seq_len(ncol(mat))+.5,ncol(mat)+.65),labels=c(colnames(mat),"Final grade"),las=2,tick=FALSE,cex.axis=.72);axis(2,at=seq_len(nrow(mat))+.5,labels=rev(rownames(mat)),las=2,tick=FALSE,cex.axis=.75);box();mtext("a",side=3,adj=-.04,font=2)
 primary<-rbind(transform(a[,common,drop=FALSE],source="First external"),transform(b[,common,drop=FALSE],source="PRJNA822526"));primary<-primary[is.finite(primary$log2FC),];par(mar=c(4,8,2,1));y<-seq_len(nrow(primary));cols<-ifelse(primary$direction_class=="direction_supported",status_col[1],ifelse(primary$direction_class=="direction_opposed",status_col[2],"#777777"));plot(primary$log2FC,rev(y),pch=ifelse(primary$source=="First external",16,17),col=cols,yaxt="n",xlab="log2 fold change",ylab="",cex=.65);abline(v=0,lty=2,col="#777777");lab<-paste(primary$genus,primary$tested_contrast,sep=" | ");axis(2,rev(y),lab,las=2,cex.axis=.42);mtext("b",side=3,adj=-.1,font=2)
 rb<-read.delim(file.path(dirname(f2),"operational_split_robustness.tsv"),check.names=FALSE);par(mar=c(4,4,2,1));plot(rb$max_single_sample_fraction,rb$leave_one_out_direction_stability,pch=19,col=ifelse(rb$marker=="ITS","#5B8FF9","#61B15A"),xlim=c(0,1),ylim=c(0,1),xlab="Maximum split fraction",ylab="Leave-one-out stability",cex=.8);abline(v=.5,h=.75,lty=2,col="#999999");mtext("c",side=3,adj=-.15,font=2);legend("bottomleft",c("ITS","16S"),pch=19,col=c("#5B8FF9","#61B15A"),bty="n",cex=.65)}
grDevices::cairo_pdf(file.path(out,"Figure_final_cross_project_evidence.pdf"),width=7.205,height=6.2,family="Arial");draw_main();dev.off();grDevices::svg(file.path(out,"Figure_final_cross_project_evidence.svg"),width=7.205,height=6.2,family="Arial",onefile=TRUE);draw_main();dev.off();grDevices::tiff(file.path(out,"Figure_final_cross_project_evidence.tiff"),width=7.205,height=6.2,units="in",res=600,compression="lzw");draw_main();dev.off()
report<-c("# 羊肚菌公共数据库外部验证：最终跨项目证据报告 v3","","## 证据边界","PRJNA935967（ITS）和PRJNA993383（16S）来自同一实验体系，合计为一个外部系统；PRJNA822526为第二个独立外部系统。公共样本不计为自有实验新增重复。","PRJNA822526每组3份为一个混合复合样本后的操作拆分，真正独立n=1，不计算推断性P值。","","## 最终等级",paste0("- ",matrix$genus,": ",matrix$final_evidence_grade," — ",matrix$grade_rationale),"","## 固定限制","- 自有M/A与测序批次重合，公共数据不能消除此限制。","- 自有连作年限与大棚完全混杂。","- 自有H/D为同一大棚两个点位的探索性比较。","- 没有产量或病情指数，不能建立预测模型。","- 相对丰度不代表绝对生物量、活菌量或因果机制。")
writeLines(report,file.path(out,"羊肚菌公共数据库外部验证_最终证据报告_v3.md"),useBytes=TRUE);writeLines(capture.output(sessionInfo()),file.path(out,"sessionInfo.txt"));writeLines(c("backend=R_base_graphics","figure_width_mm=183","formats=PDF,SVG,TIFF_600dpi","no_cross_project_ASV_merge=TRUE","no_combined_p_value=TRUE"),file.path(out,"figure_and_analysis_contract.txt"));cat("FINAL_CROSS_PROJECT_EVIDENCE_COMPLETE genera=8\n")



